chore: rename to kover (#36)
* rename

* macos testflight

* update google play

* readme

* Add Apache License 2.0

Added Apache License 2.0 to the project.

* macos testflight

* no codesign macos by default

* wrong app title

* remove android draft

* remove dep

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -59,7 +59,7 @@ jobs:
       - name: Install dependencies
         run: |
           flutter pub get
-          cd ios && pod install --repo-update
+          flutter build ios --config-only
 
       - name: Codegen
         run: |
@@ -68,6 +68,47 @@ jobs:
       - name: Build and Publish Testflight
         run: |
           cd ios
+          fastlane beta version:${{ needs.version.outputs.version }} build_number:${{ needs.version.outputs.build_number }} > /dev/null 2>&1 || (echo "Fastlane failed" && exit 1)
+        env:
+          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
+          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
+          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
+          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
+          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
+          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
+
+  build-and-deploy-macos:
+    name: Build & Deploy MacOS
+    needs: version
+    runs-on: macos-26
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Get FVM Configuration
+        uses: kuhnroyal/flutter-fvm-config-action@v3
+        id: fvm-config-action
+
+      - name: Setup Flutter
+        uses: subosito/flutter-action@v2
+        with:
+          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
+          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
+          cache: true
+
+      - name: Install dependencies
+        run: |
+          flutter pub get
+          flutter build macos --config-only
+
+      - name: Codegen
+        run: |
+          dart run build_runner build --delete-conflicting-outputs
+
+      - name: Build and Publish Testflight
+        run: |
+          cd macos
           fastlane beta version:${{ needs.version.outputs.version }} build_number:${{ needs.version.outputs.build_number }} > /dev/null 2>&1 || (echo "Fastlane failed" && exit 1)
         env:
           APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
@@ -124,7 +165,7 @@ jobs:
           KEY_ALIAS: ${{ secrets.GOOGLE_PLAY_KEYSTORE_ALIAS }}
           KEY_PASSWORD: ${{ secrets.GOOGLE_PLAY_KEY_PASSWORD }}
 
-      - name: Build and Publish Testflight
+      - name: Publish Google Play
         run: |
           cd android
           fastlane beta
@@ -160,7 +201,7 @@ jobs:
         run: |
           flutter build web \
             --release \
-            --base-href /fluvita/ \
+            --base-href /kover/ \
             --build-name ${{ needs.version.outputs.version }} \
             --build-number ${{ needs.version.outputs.build_number }} \
             --wasm
